//const Sequelize = require("sequelize");
const sequelize_db = require("../models/user");
const bcrypt = require("bcrypt");


const createUser = async (req, res) => {
    try {
      const { name, phoneNumber, email, password } = req.body;
      console.log("user details", name, phoneNumber, email, password);
      let saltround = 10;
      bcrypt.hash(password, saltround, async (err, hash) => {
        const newUser = await sequelize_db.create({
          name: name,
          phoneNumber: phoneNumber,
          email: email,
          password: hash,
          // Do not include 'id' here, as it will be auto-generated by the database
        });
        console.log("these are user details", newUser);
        return res.status(200).json({ sign_up: newUser, message: "posted data" });
      });
    } catch (error) {
      console.log(error);
      return res.status(500).json({ error: "Failed to create user." });
    }
  };
  

  module.exports = { createUser };